// ══════════════════════════════════════════
//  data.js
//  All static programme data.
//  Edit this file to change exercises — nothing else needs touching.
// ══════════════════════════════════════════

const PROGRAM = [
  {
    id: 'chest-biceps',
    label: 'Day 1',
    focus: 'Chest & Biceps',
    equipment: ['Barbell (5ft)', 'Dumbbells', 'Incline Bench', 'Flat Bench'],
    exercises: [
      {
        name: 'Incline Bench Press',
        sets: 5,
        reps: '15/15/12/12/10',
        defaultWeight: 30,
        equipment: ['Barbell (5ft)', 'Incline Bench'],
        alternative: {
          name: 'Incline Dumbbell Press',
          equipment: ['Dumbbells', 'Incline Bench'],
        },
      },
      {
        name: 'Bench Press',
        sets: 4,
        reps: '12/10/8/8',
        defaultWeight: 30,
        equipment: ['Barbell (5ft)', 'Flat Bench'],
        alternative: {
          name: 'Dumbbell Chest Press',
          equipment: ['Dumbbells', 'Flat Bench'],
        },
      },
      {
        name: 'Incline Dumbbell Flys',
        sets: 3,
        reps: '15/12/12',
        defaultWeight: 12.5,
        equipment: ['Dumbbells', 'Incline Bench'],
        alternative: { name: 'Wide Push-ups', equipment: [] },
      },
      {
        name: 'Barbell Curls',
        sets: 3,
        reps: '15/15/15',
        defaultWeight: null,
        equipment: ['Barbell (5ft)'],
        alternative: { name: 'Dumbbell Curls', equipment: ['Dumbbells'] },
        superset: {
          name: 'Reverse Barbell Curls',
          reps: 'Failure',
          defaultWeight: null,
          equipment: ['Barbell (5ft)'],
          alternative: {
            name: 'Reverse Dumbbell Curls',
            equipment: ['Dumbbells'],
          },
        },
      },
      {
        name: 'Push-ups (finisher)',
        sets: 1,
        reps: 'Failure',
        defaultWeight: null,
        equipment: [],
      },
    ],
  },
  {
    id: 'back',
    label: 'Day 2',
    focus: 'Back',
    equipment: ['Barbell (7ft)', 'Dumbbells', 'Flat Bench'],
    exercises: [
      {
        name: 'Deadlifts',
        sets: 4,
        reps: '10/8/8/Fail',
        defaultWeight: 62,
        equipment: ['Barbell (7ft)'],
        alternative: { name: 'Dumbbell Deadlifts', equipment: ['Dumbbells'] },
      },
      {
        name: 'Bent Over Rows',
        sets: 4,
        reps: '12/10/10/8',
        defaultWeight: 35,
        note: '2 underhand, 2 overhand',
        equipment: ['Barbell (7ft)'],
        alternative: {
          name: 'Dumbbell Rows',
          equipment: ['Dumbbells', 'Flat Bench'],
        },
      },
      {
        name: 'Power Shrug',
        sets: 3,
        reps: '12/12/12',
        defaultWeight: 62,
        equipment: ['Barbell (7ft)'],
        alternative: { name: 'Dumbbell Shrugs', equipment: ['Dumbbells'] },
      },
      {
        name: 'Chest Supported Row',
        sets: 4,
        reps: '12/10/10/8',
        defaultWeight: 17.5,
        equipment: ['Chest Supported Row Machine'],
        alternative: {
          name: 'Dumbbell Rows',
          equipment: ['Dumbbells', 'Flat Bench'],
        },
      },
    ],
  },
  {
    id: 'ham-glutes',
    label: 'Day 3',
    focus: 'Hamstrings & Glutes',
    equipment: ['Barbell (7ft)', 'Flat Bench'],
    exercises: [
      {
        name: 'Lying Leg Curls',
        sets: 4,
        reps: '15/15/15/15',
        defaultWeight: 35,
        equipment: ['Leg Curl Machine'],
        alternative: { name: 'Nordic Curls', equipment: ['Flat Bench'] },
      },
      {
        name: 'Straight-Legged Deadlifts',
        sets: 4,
        reps: '15-20 each',
        defaultWeight: 47.5,
        equipment: ['Barbell (7ft)'],
        alternative: {
          name: 'Dumbbell Straight-Legged Deadlifts',
          equipment: ['Dumbbells'],
        },
      },
      {
        name: 'Front Barbell Squat',
        sets: 4,
        reps: '15/15/15/15',
        defaultWeight: 30,
        equipment: ['Barbell (7ft)', 'Squat Rack'],
        alternative: { name: 'Goblet Squat', equipment: ['Dumbbells'] },
      },
      {
        name: 'Barbell Hip Thrusts',
        sets: 3,
        reps: '8-10 each',
        defaultWeight: 30,
        equipment: ['Barbell (7ft)', 'Flat Bench'],
        alternative: {
          name: 'Bodyweight Hip Thrusts',
          equipment: ['Flat Bench'],
        },
      },
    ],
  },
  {
    id: 'shoulders-tri',
    label: 'Day 4',
    focus: 'Shoulders & Triceps',
    equipment: ['Barbell (5ft)', 'Dumbbells', 'Flat Bench'],
    exercises: [
      {
        name: 'Dumbbell Shoulder Press',
        sets: 3,
        reps: '12/12/12',
        defaultWeight: 15,
        equipment: ['Dumbbells'],
        alternative: {
          name: 'Barbell Shoulder Press',
          equipment: ['Barbell (5ft)'],
        },
        superset: {
          name: 'Barbell Front Raise',
          reps: '12/12/12',
          defaultWeight: 10,
          equipment: ['Barbell (5ft)'],
          alternative: {
            name: 'Dumbbell Front Raise',
            equipment: ['Dumbbells'],
          },
        },
      },
      {
        name: 'Dumbbell Lateral Raises 1½',
        sets: 3,
        reps: '12-15',
        defaultWeight: 5,
        equipment: ['Dumbbells'],
        alternative: { name: 'Plate Lateral Raises', equipment: [] },
      },
      {
        name: 'Upright Rows',
        sets: 3,
        reps: '15/12/12',
        defaultWeight: null,
        equipment: ['Barbell (5ft)'],
        alternative: {
          name: 'Dumbbell Upright Rows',
          equipment: ['Dumbbells'],
        },
        superset: {
          name: 'Dumbbell Rows',
          reps: '15/12/12',
          defaultWeight: null,
          equipment: ['Dumbbells', 'Flat Bench'],
          alternative: { name: 'Bodyweight Rows', equipment: [] },
        },
      },
      {
        name: 'Bench Dips',
        sets: 3,
        reps: '12-15',
        defaultWeight: null,
        equipment: ['Flat Bench'],
        alternative: { name: 'Diamond Push-ups', equipment: [] },
        superset: {
          name: 'Skull Crushers',
          reps: '12-15',
          defaultWeight: 7.5,
          equipment: ['Barbell (5ft)', 'Flat Bench'],
          alternative: {
            name: 'Dumbbell Skull Crushers',
            equipment: ['Dumbbells', 'Flat Bench'],
          },
        },
      },
    ],
  },
  {
    id: 'quads',
    label: 'Day 5',
    focus: 'Quads',
    equipment: ['Barbell (7ft)', 'Squat Rack', 'Flat Bench'],
    exercises: [
      {
        name: 'Squats (heavy)',
        sets: 2,
        reps: '8/8',
        defaultWeight: 50,
        equipment: ['Barbell (7ft)', 'Squat Rack'],
        alternative: {
          name: 'Dumbbell Goblet Squats',
          equipment: ['Dumbbells'],
        },
      },
      {
        name: 'Squats (lighter)',
        sets: 3,
        reps: '10-12 each',
        defaultWeight: 35,
        equipment: ['Barbell (7ft)', 'Squat Rack'],
        alternative: {
          name: 'Dumbbell Goblet Squats',
          equipment: ['Dumbbells'],
        },
      },
      {
        name: 'Bulgarian Split Squats',
        sets: 3,
        reps: '10-12 each',
        defaultWeight: null,
        equipment: ['Flat Bench'],
        alternative: { name: 'Reverse Lunges', equipment: [] },
      },
      {
        name: 'Leg Extensions',
        sets: 4,
        reps: '15 each',
        defaultWeight: null,
        equipment: ['Leg Extension Machine'],
        alternative: { name: 'Sissy Squats', equipment: [] },
        superset: {
          name: 'Standing Lunges',
          reps: '6-8 each',
          defaultWeight: null,
          equipment: [],
          alternative: null,
        },
      },
    ],
  },
];

const EQUIPMENT_LIST = [
  'Squat Rack',
  'Barbell (7ft)',
  'Barbell (5ft)',
  'Dumbbells',
  'Flat Bench',
  'Incline Bench',
  'Leg Curl Machine',
  'Leg Extension Machine',
  'Leg Press Machine',
  'Chest Supported Row Machine',
  'Resistance Bands',
  'Pull Up Bar',
];

const WARMUPS = {
  'chest-biceps': [
    {
      name: 'Thoracic Rotations',
      description: 'Sit or kneel, hands behind head. Rotate upper back left and right, keeping hips still.',
      type: 'reps',
      reps: '10 each side',
      equipment: [],
    },
    {
      name: 'Arm Swings',
      description: 'Stand tall. Swing both arms across your chest and back out wide in a controlled arc.',
      type: 'timed',
      duration: 30,
      equipment: [],
    },
    {
      name: 'Doorframe Chest Stretch',
      description: 'Place forearms on a doorframe at 90°. Step forward until you feel a stretch across the chest. Hold.',
      type: 'timed',
      duration: 30,
      equipment: [],
    },
    {
      name: 'Light Incline Press',
      description: 'Same movement as your first working set — focus on path and feel, not load.',
      type: 'reps',
      reps: '15',
      equipment: ['Barbell (5ft)', 'Incline Bench'],
      weightNote: 'Use ~20% of working weight',
    },
    {
      name: 'Light Dumbbell Curl',
      description: 'Full range curl, slow on the way down. Wrist stays neutral throughout.',
      type: 'reps',
      reps: '12',
      equipment: ['Dumbbells'],
      weightNote: 'Use ~20% of working weight',
    },
  ],

  back: [
    {
      name: 'Cat-Cow',
      description: 'On hands and knees. Inhale — drop belly, lift head. Exhale — round spine, tuck chin. Slow and deliberate.',
      type: 'reps',
      reps: '10',
      equipment: [],
    },
    {
      name: 'Hip Hinge Drill',
      description: 'Stand tall. Hinge at the hips until you feel your hamstrings load, keeping your back flat. Squeeze glutes to stand.',
      type: 'reps',
      reps: '12',
      equipment: [],
    },
    {
      name: 'Scapular Pulls',
      description: 'Hang from a bar with arms straight. Without bending your elbows, depress and retract your shoulder blades. Hold 1 sec at the top.',
      type: 'reps',
      reps: '8',
      equipment: ['Pull Up Bar'],
    },
    {
      name: 'Light Deadlift',
      description: 'Movement rehearsal — brace your core, push the floor away, feel the lats engage before the bar leaves the ground.',
      type: 'reps',
      reps: '8',
      equipment: ['Barbell (7ft)'],
      weightNote: 'Use ~20% of working weight',
    },
    {
      name: 'Light Bent Over Row',
      description: 'Hinge to your working position, pull to your lower chest. Pause at the top, lower with control.',
      type: 'reps',
      reps: '10',
      equipment: ['Barbell (7ft)'],
      weightNote: 'Use ~20% of working weight',
    },
  ],

  'ham-glutes': [
    {
      name: 'Standing Hip Flexor Stretch',
      description: 'Lunge forward, drop your back knee. Drive your hip forward and hold. Keep your torso tall.',
      type: 'timed',
      duration: 30,
      equipment: [],
    },
    {
      name: 'Leg Swings',
      description: 'Hold a wall for support. Swing each leg forward and back in a controlled arc, gradually increasing range.',
      type: 'reps',
      reps: '12 each leg',
      equipment: [],
    },
    {
      name: 'Glute Bridges',
      description: 'Lie on your back, feet flat on the floor. Drive through your heels, squeeze glutes at the top. Hold for 1 second.',
      type: 'reps',
      reps: '15',
      equipment: [],
    },
    {
      name: 'Light RDL',
      description: 'Feel the hamstrings load as you hinge. Push hips back, not down. This is about range and tension — not load.',
      type: 'reps',
      reps: '10',
      equipment: ['Barbell (7ft)'],
      weightNote: 'Use ~20% of working weight',
    },
  ],

  'shoulders-tri': [
    {
      name: 'Shoulder CARs',
      description: 'Slow, controlled circular rotation of the shoulder through its full range. Keep the rest of your body completely still.',
      type: 'reps',
      reps: '5 each direction, each arm',
      equipment: [],
    },
    {
      name: 'Wall Slides',
      description: 'Back flat against a wall, arms in a goalpost position. Slide arms overhead while keeping your wrists, elbows and back in contact.',
      type: 'reps',
      reps: '10',
      equipment: [],
    },
    {
      name: 'Band Pull-Aparts',
      description: 'Hold a band at shoulder height with arms extended. Pull apart until it touches your chest, squeezing your shoulder blades together.',
      type: 'reps',
      reps: '15',
      equipment: ['Resistance Bands'],
    },
    {
      name: 'Light Lateral Raise',
      description: 'Lead with your elbows, not your hands. Stop at shoulder height. Slow and controlled — no swinging.',
      type: 'reps',
      reps: '15',
      equipment: ['Dumbbells'],
      weightNote: 'Use ~20% of working weight',
    },
    {
      name: 'Light Shoulder Press',
      description: 'Press straight overhead, lock out at the top, lower slowly. Primes the rotator cuff before heavier work.',
      type: 'reps',
      reps: '12',
      equipment: ['Dumbbells'],
      weightNote: 'Use ~20% of working weight',
    },
  ],

  quads: [
    {
      name: 'Hip Circles',
      description: 'Stand on one leg, draw large circles with your opposite knee. Keeps the hip joint mobile before loading.',
      type: 'reps',
      reps: '10 each direction, each leg',
      equipment: [],
    },
    {
      name: 'Bodyweight Squats',
      description: 'Full depth. Pause for 1 second at the bottom. Knees track over toes, chest stays tall.',
      type: 'reps',
      reps: '15',
      equipment: [],
    },
    {
      name: 'Walking Lunges',
      description: 'Long stride, back knee grazes the floor. Drive off your front foot to stand. Alternating legs.',
      type: 'reps',
      reps: '10 each leg',
      equipment: [],
    },
    {
      name: 'Light Squat',
      description: 'Same bar position and depth as your working sets. Lock in your stance and brace pattern before adding load.',
      type: 'reps',
      reps: '10',
      equipment: ['Barbell (7ft)', 'Squat Rack'],
      weightNote: 'Use ~20% of working weight',
    },
  ],
};